###
### Containerfile.test - used to test akmods
###

ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-40}"
ARG BUILDER_IMAGE="${BUILDER_IMAGE:-quay.io/fedora/fedora}"
ARG BUILDER_BASE="${BUILDER_IMAGE}:${FEDORA_MAJOR_VERSION}"
ARG INPUT_AKMODS="${INPUT_AKMODS:-akmods}"
ARG INPUT_TAG="${INPUT_TAG:-${KERNEL_FLAVOR}-${FEDORA_MAJOR_VERSION}}"
ARG INPUT_BASE="${INPUT_AKMODS}:${INPUT_TAG}"
FROM ${INPUT_BASE} AS akmods_cache
FROM ${BUILDER_BASE} AS tester

ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-40}"
ARG KERNEL_FLAVOR="${KERNEL_FLAVOR:-main}"
ARG RPMFUSION_MIRROR=""
ARG DUAL_SIGN="true"

COPY build_files/shared /tmp/
COPY certs /tmp/certs

# cached kernel rpms
COPY --from=akmods_cache /kernel-rpms /tmp/kernel_cache
COPY --from=akmods_cache /rpms /tmp/akmods-rpms

RUN --mount=type=cache,dst=/var/cache/dnf \
    if grep -qv "surface" <<< "${KERNEL_FLAVOR}"; then \
        export KERNEL_NAME="kernel" \
    ; else \
        export KERNEL_NAME="kernel-surface" \
    ; fi && \
    /tmp/test-prep.sh

CMD ["/tmp/check-signatures.sh"]
