FROM BUILDER AS build_prep

ARG DUAL_SIGN="true"
ARG KERNEL_FLAVOR_ARG
ARG KERNEL_NAME_ARG
ARG RPMFUSION_MIRROR_ARG
ARG VERSION_ARG

#ifdef CI_SETX
ARG CI=1
#endif /* CI_SETX */

#ifdef NVIDIA
ARG KMOD_REPO_ARG
#endif /* NVIDIA */

# /*
# common copy/add
# */

COPY certs /tmp/certs

#ifndef CENTOS
ADD https://copr.fedorainfracloud.org/coprs/austinzhang1024/xone/repo/fedora-${VERSION}/ublue-os-akmods-fedora-${VERSION}.repo\
    /tmp/ublue-os-akmods-addons/rpmbuild/SOURCES/_copr_ublue-os-akmods.repo
ADD https://negativo17.org/repos/fedora-multimedia.repo \
    /tmp/ublue-os-akmods-addons/rpmbuild/SOURCES/negativo17-fedora-multimedia.repo
ADD https://raw.githubusercontent.com/terrapkg/packages/f${VERSION}/anda/terra/release/terra.repo \
    /tmp/ublue-os-akmods-addons/rpmbuild/SOURCES/terra.repo
ADD https://raw.githubusercontent.com/terrapkg/packages/f${VERSION}/anda/terra/gpg-keys/RPM-GPG-KEY-terra${VERSION} \
    /tmp/ublue-os-akmods-addons/rpmbuild/SOURCES/RPM-GPG-KEY-terra${VERSION}
#endif

# /*
# Preperation
# */
COPY build_files/prep /tmp/
RUN --mount=type=cache,dst=/var/cache/dnf \
    --mount=type=cache,dst=/var/cache/libdnf5 \
    bash <<'RUNEOF'
set ${CI+-x} -euo pipefail
ls -sh /tmp/kernel_cache
/tmp/build-prep.sh
RUNEOF

FROM build_prep AS builder

ARG DUAL_SIGN="true"
ARG KERNEL_FLAVOR_ARG
ARG KERNEL_NAME_ARG
ARG RPMFUSION_MIRROR_ARG
ARG VERSION_ARG

#ifdef CI_SETX
ARG CI=1
#endif /* CI_SETX */


COPY build_files/common /tmp/
RUN --mount=type=cache,dst=/var/cache/dnf \
    --mount=type=cache,dst=/var/cache/libdnf5 \
    bash <<'RUNEOF'
set ${CI+-x} -euo pipefail
/tmp/build-ublue-os-akmods-addons.sh
cp /tmp/ublue-os-akmods-addons/rpmbuild/RPMS/noarch/ublue-os-akmods-addons*.rpm /var/cache/rpms/ublue-os/
RUNEOF
RUN --mount=type=cache,dst=/var/cache/dnf \
    --mount=type=cache,dst=/var/cache/libdnf5 \
    bash <<'RUNEOF'
/tmp/build-kmod-framework-laptop.sh
/tmp/build-kmod-openrazer.sh
/tmp/build-kmod-v4l2loopback.sh
/tmp/build-kmod-wl.sh
/tmp/build-kmod-xpadneo.sh
/tmp/build-kmod-xone.sh
RUNEOF


# /*
# Signing
# */
COPY build_files/post /tmp/
RUN --mount=type=cache,dst=/var/cache/dnf \
    --mount=type=cache,dst=/var/cache/libdnf5 \
    bash <<'RUNEOF'
set ${CI+-x} -euo pipefail
#ifdef ZFS
/tmp/dual-sign-zfs.sh
#else
/tmp/dual-sign.sh
#endif /* ZFS */
/tmp/build-post.sh
RUNEOF

FROM scratch AS RPM_CACHE

COPY --from=builder /var/cache/kernel-rpms /kernel-rpms
COPY --from=builder /var/cache/rpms /rpms

FROM build_prep AS test

ARG DUAL_SIGN="true"
ARG KERNEL_FLAVOR_ARG
ARG KERNEL_NAME_ARG
ARG RPMFUSION_MIRROR_ARG
ARG VERSION_ARG

#ifdef NVIDIA 
ARG KMOD_REPO_ARG
#endif /* NVIDIA */

#ifdef CI_SETX
ENV CI=1
#endif

COPY --from=RPM_CACHE /kernel-rpms /tmp/kernel_cache
COPY --from=RPM_CACHE /rpms /tmp/akmods-rpms

COPY build_files/test/test-prep.sh /tmp/
COPY certs /tmp/certs

RUN --mount=type=cache,dst=/var/cache/dnf \
    --mount=type=cache,dst=/var/cache/libdnf5 \
    bash <<'RUNEOF'
set ${CI+-x} -euo pipefail
/tmp/test-prep.sh
RUNEOF

COPY build_files/test/check-signatures.sh /tmp/
CMD ["/tmp/check-signatures.sh"]

FROM scratch AS RPMS
COPY --from=RPM_CACHE / /
