name: ublue akmods 39
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 14 * * *'  # 2pm-ish UTC everyday (timed against official fedora container pushes, and after 'config')
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 39